#:kivy 1.0.9

#global property Flexible_input

<Plain_button>:
    background_normal:'plain_button.png'
    background_down: 'plain_button_dep.png'

<Common_button>:
    background_normal:'button.png'
    background_down: 'button_dep.png'

<Flexible_Input>:
    use_bubble: True
    focus: True
    size_hint_x: 2
    font_size: "15dp"
    padding_x: 50
    hint_text_color: [0, 0, 0, 0.2]
    multiline: False
    
#:include api_bar.kv
#:include params_panel.kv

# #:import Clock kivy.clock.Clock

